worker_processes 1;

events {
    worker_connections 1024;
}

http {
    proxy_cache_path /tmp/cache keys_zone=cache:10m levels=1:2 inactive=600s max_size=100m;

    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {

        proxy_cache cache;
        proxy_cache_lock on;
        proxy_cache_valid 200 10s;
        proxy_cache_use_stale updating;

        server_name api.coinscan.finance;

        location / {
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' 'https://coinscan.finance';
                add_header 'Access-Control-Allow-Credentials' 'true';
                add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';

                add_header 'Access-Control-Allow-Headers' 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Api-Auth';

                return 204;
            }

            if ($request_method = 'GET') {
                add_header 'Access-Control-Allow-Origin' 'https://coinscan.finance';
                add_header 'Access-Control-Allow-Credentials' 'true';
                add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Api-Auth';
            }

            proxy_pass http://localhost:8888/;
            index index.html index.htm;
        
        } # end location

        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/api.coinscan.finance/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/api.coinscan.finance/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    } # end server


    server {
        if ($host = api.coinscan.finance) {
            return 301 https://$host$request_uri;
        } # managed by Certbot

        listen 80;
        server_name api.coinscan.finance;
        return 404; # managed by Certbot


    }
} # end http