worker_processes 1;

events {
    worker_connections 1024;
}

http {

    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {

        server_name api.coinscan.finance;

        location / {
            proxy_pass http://localhost:8888/;
            index index.html index.htm;
        
        } # end location

        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/api.coinscan.finance/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/api.coinscan.finance/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    } # end server


    server {
        if ($host = api.coinscan.finance) {
            return 301 https://$host$request_uri;
        } # managed by Certbot

        listen 80;
        server_name api.coinscan.finance;
        return 404; # managed by Certbot


    }
} # end http